export type { Database, Json } from './types.gen';
export {
  createRackClient,
  readSupabaseConfig,
  type RackClient,
  type SupabaseConfig,
} from './client';
export {
  chunkedStore,
  splitIntoChunks,
  type ChunkedStoreOptions,
  type KeyValueStore,
} from './chunked-storage';
export {
  chooseActiveTenant,
  findMembershipBySlug,
  fetchMe,
  hasRequiredAction,
  BookingRulesSchema,
  CurrentTenantSchema,
  MembershipSchema,
  MeSchema,
  MeUserSchema,
  TenantThemeSchema,
  MEMBERSHIP_ROLES,
  MEMBERSHIP_STATUSES,
  REQUIRED_ACTIONS,
  type BookingRules,
  type CurrentTenant,
  type Me,
  type Membership,
  type RequiredAction,
  type TenantTheme,
} from './me';
export {
  DirectoryRowSchema,
  ImportResultSchema,
  importMembers,
  type ImportResult,
  INVITATION_STATES,
  createInvitation,
  displayName,
  filterDirectory,
  grantableRoles,
  invitationState,
  removeMember,
  setMemberRole,
  type DirectoryFilter,
  type DirectoryRow,
  type InvitationState,
} from './staff';

export {
  acceptInvitation,
  fetchTenantPublicProfile,
  InvitationPreviewSchema,
  PendingInvitationSchema,
  acceptPendingInvitation,
  fetchPendingInvitations,
  type PendingInvitation,
  TenantPublicProfileSchema,
  fetchInvitationPreview,
  invitationAcceptsEmail,
  type InvitationPreview,
  type TenantPublicProfile,
} from './tenant';
export { INVITATION_PATH_SEGMENT, invitationPath } from './invitation-link';
export {
  fetchPolicyVersion,
  isPlatformConsent,
  fetchMyPreferences,
  recordConsents,
  setRosterVisibility,
  type MyPreferences,
  updateLocale,
  updateProfile,
  CONSENT_PURPOSES,
  PLATFORM_CONSENT_PURPOSES,
  ProfilePatchSchema,
  type ConsentChoice,
  type ConsentPurpose,
  type ProfilePatch,
  type RecordConsentsInput,
} from './profile';
export {
  BoxAppearanceSchema,
  FONT_OPTIONS,
  UNCONFIGURED_BOX_PRIMARY,
  fontOptions,
  type BoxAppearance,
} from './appearance';

export {
  BookingRulesPatchSchema,
  BoxIdentitySchema,
  ClassTypePatchSchema,
  DEFAULT_CLASS_TYPE_COLOR,
  LocalizedTextSchema,
  LocationPatchSchema,
  OpeningHourSchema,
  RoomPatchSchema,
  TIME_ZONE_OPTIONS,
  WEEKDAYS,
  isSupportedTimeZone,
  localizedText,
  normalizeTime,
  overlappingSlots,
  timeZoneOptions,
  type BookingRulesPatch,
  type BoxIdentity,
  type ClassTypePatch,
  type LocalizedText,
  type LocationPatch,
  type OpeningHour,
  type RoomPatch,
  type Weekday,
} from './box-settings';

export {
  ClassSchedulePatchSchema,
  RecurrenceSchema,
  RRULE_DAYS,
  RRULE_MAX_INTERVAL,
  RRULE_MIN_INTERVAL,
  buildWeeklyRrule,
  dayOfWeekday,
  isCalendarDate,
  isPilotRrule,
  mondayOf,
  parseWeeklyRrule,
  shiftDays,
  shiftWeeks,
  weekDates,
  weekdayOf,
  type ClassSchedulePatch,
  type RruleDay,
  type WeeklyRecurrence,
} from './class-schedules';
export {
  CoachRowSchema,
  DAY_SCHEDULE_TIMEOUT_MS,
  coachDisplayName,
  DAY_LABELS,
  DayScheduleSchema,
  fetchDaySchedule,
  groupByDay,
  instantLocal,
  localDay,
  localDayIn,
  seatsLeft,
  type Choice,
  type DayClass,
  type DaySchedule,
  type Occurrence,
  type Serie,
} from './planning';

export {
  tenantScope,
  type TenantInsert,
  type TenantScope,
  type TenantScopedRelation,
  type TenantScopedTable,
  type TenantScopedView,
} from './active-tenant';

export {
  BookingFailed,
  affordanceHint,
  affordanceLabelKey,
  bookClass,
  bookingAffordance,
  fetchClassDetail,
  fetchClassRoster,
  fetchUpcomingBookings,
  type AffordanceClass,
  type AffordanceInput,
  type AffordanceRules,
  type BookClassInput,
  type BookClassOptions,
  type BookingAffordance,
  type ClassDetail,
  type RosterPeer,
  type UpcomingBooking,
} from './bookings';
